<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        DB::table('subjects')->insert([
            ['name' => 'Electronics'],
            ['name' => 'Computers']
        ]);

        DB::table('categories')->insert([
            [ 'name'=>'Cell Phones And Accesories', 'subject_id'=>1, 'page_title'=>null, 'page_text'=>null, 'page_file'=>null ],
            [ 'name'=>'Laptop And Acssesories', 'subject_id'=>2, 'page_title'=>null, 'page_text'=>null, 'page_file'=>null ],
            [ 'name'=>'Display', 'subject_id'=>2, 'page_title'=>null, 'page_text'=>null, 'page_file'=>null ],
            [ 'name'=>'Speakers And Sound', 'subject_id'=>1, 'page_title'=>null, 'page_text'=>null, 'page_file'=>null ],
        ]);

        DB::table('sub_categories')->insert([
            [ 'name'=>'Cell Phones', 'category_id'=>1],
            [ 'name'=>'Laptops', 'category_id'=>2],
            [ 'name'=>'Monitors', 'category_id'=>3],
            [ 'name'=>'Headphones', 'category_id'=>4 ],
        ]);

        DB::table('products')->insert([
            [ 'title'=>'Samsung Galaxy Note 20 Ultra', 'full_name'=>'5G Factory Unlocked Android Cell Phone 128GB US Version Mobile Gaming Smartphone Long-Lasting Battery, Mystic White', 'price'=>1560, 'quantity'=>864, 'discount'=>5, 'sales'=>7, 'subcategory_id'=>1, ],
            [ 'title'=>'Apple iPhone 11 Pro', 'full_name'=>'64GB, Space Gray - Unlocked (Renewed Premium)', 'price'=>1125, 'quantity'=>68, 'discount'=>5, 'sales'=>1, 'subcategory_id'=>1, ],
            [ 'title'=>'Apple iPhone 12 Pro', 'full_name'=>'128GB, Pacific Blue - Unlocked (Renewed Premium)', 'price'=>1234, 'quantity'=>12, 'discount'=>3, 'sales'=>2, 'subcategory_id'=>1, ],
            [ 'title'=>'Apple iPhone 8 Plus', 'full_name'=>'US Version, 64GB, Gold - AT&T (Renewed)', 'price'=>976, 'quantity'=>76, 'discount'=>2, 'sales'=>1, 'subcategory_id'=>1, ],
            [ 'title'=>'SAMSUNG Galaxy S20 FE 5G', 'full_name'=>'Factory Unlocked Android Cell Phone 128GB US Version Smartphone Pro-Grade Camera 30X Space Zoom Night Mode, Cloud Navy', 'price'=>876, 'quantity'=>67, 'discount'=>2, 'sales'=>12, 'subcategory_id'=>1, ],
            [ 'title'=>'Samsung Electronics Galaxy Z Fold 3 5G', 'full_name'=>'Factory Unlocked Android Cell Phone US Version Smartphone Tablet 2-in-1 Foldable Dual Screen Under Display Camera 256GB Storage, Phantom Black', 'price'=>1454, 'quantity'=>111, 'discount'=>1, 'sales'=>1, 'subcategory_id'=>1, ],
            [ 'title'=>'SAMSUNG Galaxy Z Flip 3 5G', 'full_name'=>'Factory Unlocked Android Cell Phone US Version Smartphone Flex Mode Intuitive Camera Compact 128GB Storage US Warranty, Green"', 'price'=>1808, 'quantity'=>123, 'discount'=>0, 'sales'=>1, 'subcategory_id'=>1, ],
            [ 'title'=>'Huawei P50 Pro', 'full_name'=>'JAD-AL50 256GB 8GB RAM Factory Unlocked (GSM Only | No CDMA - not Compatible with Verizon/Sprint) No Google Play Installed China Version – Gold', 'price'=>689, 'quantity'=>121, 'discount'=>3, 'sales'=>5, 'subcategory_id'=>1, ],
            [ 'title'=>'ASUS Laptop L510', 'full_name'=>'Ultra Thin Laptop, 15.6” FHD Display, Intel Celeron N4020 Processor, 4GB RAM, 128GB Storage, Windows 10 Home in', 'price'=>343, 'quantity'=>7654, 'discount'=>1, 'sales'=>null, 'subcategory_id'=>2, ],
            [ 'title'=>'ASUS TUF Dash 15 (2021) Ultra Slim', 'full_name'=>'Gaming Laptop, 15.6” 144Hz FHD, GeForce RTX 3050 Ti, Intel Core i7-11370H, 8GB DDR4, 512GB PCIe NVMe SSD, Wi-Fi 6', 'price'=>1060, 'quantity'=>53, 'discount'=>0, 'sales'=>null, 'subcategory_id'=>2, ],
            [ 'title'=>'ASUS VivoBook 15 OLED K513', 'full_name'=>'Thin & Light Laptop, 15.6 OLED Display, Intel i5-1135G7 CPU, Intel Iris X Graphics, 12GB RAM, 512GB PCIe SSD, Fingerprint Reader', 'price'=>810, 'quantity'=>12, 'discount'=>2, 'sales'=>null, 'subcategory_id'=>2, ],
            [ 'title'=>'ASUS ZenBook 14 Ultra-Slim Laptop 14', 'full_name'=>'Full HD NanoEdge Display, Intel Core i7-1165G7, 8GB RAM, 512GB PCIe SSD, NumberPad', 'price'=>939, 'quantity'=>777, 'discount'=>1, 'sales'=>17, 'subcategory_id'=>2, ],
            [ 'title'=>'ASUS ZenBook 13 Ultra-Slim', 'full_name'=>'13.3” OLED FHD NanoEdge Bezel Display, Intel Core i7-1165G7, 8GB LPDDR4X RAM, 512GB SSD, NumberPad', 'price'=>950, 'quantity'=>12, 'discount'=>1, 'sales'=>null, 'subcategory_id'=>2, ],
            [ 'title'=>'2017 Apple MacBook Air', 'full_name'=>'with 1.8GHz Intel Core i5 (13-inch, 8GB RAM, 128GB SSD Storage)', 'price'=>555, 'quantity'=>32, 'discount'=>20, 'sales'=>null, 'subcategory_id'=>2, ],
            [ 'title'=>'ASUS ZenBook Duo 14 UX482', 'full_name'=>'4” FHD NanoEdge Touch Display, Intel Core i7-1165G7 CPU, NVIDIA GeForce MX450, 32GB RAM, 1TB SSD', 'price'=>2070, 'quantity'=>68, 'discount'=>1, 'sales'=>null, 'subcategory_id'=>2, ],
            [ 'title'=>'Lenovo IdeaPad 15.6', 'full_name'=>'FHD Touchscreen Laptop, Intel Core i5-1135G7 Quad-Core Processor (Beats i7-1065G7), Intel Iris Xe Graphics, 20GB RAM', 'price'=>710, 'quantity'=>1212, 'discount'=>1, 'sales'=>null, 'subcategory_id'=>2, ],
            [ 'title'=>'Lenovo IdeaPad 3 Laptop', 'full_name'=>'5.6" FHD Display, AMD Ryzen 5, 8GB RAM, 512GB Storage, AMD Radeon 7', 'price'=>560, 'quantity'=>98, 'discount'=>1, 'sales'=>null, 'subcategory_id'=>2, ],
            [ 'title'=>'Lenovo IdeaPad 3 15.6"', 'full_name'=>'Touchscreen Laptop - AMD Ryzen 5 5500U - Abyss Blue MD Ryzen 5 5500U 12GB DDR4 2666MHz RAM 512GB', 'price'=>620, 'quantity'=>87, 'discount'=>10, 'sales'=>null, 'subcategory_id'=>2, ],
            [ 'title'=>'Samsung CF390 Series 27 inch FHD', 'full_name'=>'1920x1080 Curved Desktop Monitor for Business, HDMI, VGA, VESA mountable, 3-Year Warranty', 'price'=>198, 'quantity'=>568, 'discount'=>1, 'sales'=>null, 'subcategory_id'=>3, ],
            [ 'title'=>'ASUS TUF Gaming 27" 2K HDR Gaming Monitor', 'full_name'=>'(VG27AQ) - WQHD (2560 x 1440), 165Hz (Supports 144Hz), 1ms, Extreme Low Motion Blur, Speaker, G-SYNC Compatible', 'price'=>349, 'quantity'=>123, 'discount'=>1, 'sales'=>null, 'subcategory_id'=>3, ],
            [ 'title'=>'ASUS ProArt Display 27', 'full_name'=>'Monitor PA278CV - WQHD (2560 x 1440), IPS, 100% sRGB, 100% Rec. 709, ΔE < 2, Calman Verified, USB Hub, USB-C', 'price'=>512, 'quantity'=>1221, 'discount'=>12, 'sales'=>null, 'subcategory_id'=>3, ],
            [ 'title'=>'ASUS VA24DQ 23.8”', 'full_name'=>'Monitor, 1080P Full HD, 75Hz, IPS, Adaptive-Sync/FreeSync, Eye Care, HDMI DisplayPort VGA', 'price'=>200, 'quantity'=>213, 'discount'=>10, 'sales'=>null, 'subcategory_id'=>3, ],
            [ 'title'=>'Sony WI-XB400 Wireless in-Ear', 'full_name'=>'Extra Bass Headset/Headphones with mic for Phone Call, Blue (WIXB400/L)', 'price'=>17, 'quantity'=>54, 'discount'=>1, 'sales'=>null, 'subcategory_id'=>4, ],
            [ 'title'=>'Sony Wireless RF Headphone', 'full_name'=>'150-Foot Range, Noise Reduction, Volume Control, Voice Mode, 20-Hr Battery Life –NeeGo 6-ft 3.5mm RCA Plug Y-Adapter for TV', 'price'=>140, 'quantity'=>654, 'discount'=>1, 'sales'=>null, 'subcategory_id'=>4, ],
            [ 'title'=>'Sony True Wireless Bluetooth', 'full_name'=>'in Ear Headphones: Noise Cancelling Sports Workout Ear Buds - Cordless, Sweatproof Earphones, Built-in Microphone, Extra BASS WF-SP700N/B (International Version) Black', 'price'=>55, 'quantity'=>65, 'discount'=>1, 'sales'=>null, 'subcategory_id'=>4, ],
            [ 'title'=>'Sony ZX Series Wired', 'full_name'=>'On-Ear Headphones, Black MDR-ZX110', 'price'=>123, 'quantity'=>12, 'discount'=>11, 'sales'=>null, 'subcategory_id'=>4, ],
        ]);

        DB::table('about_products')->insert([
            [ 'text'=>'S PEN & SAMSUNG NOTES: Pen precision meets PC power with S Pen & Samsung Notes. So responsive, it feels like you\'re using a real pen.', 'product_id'=>1 ],
            [ 'text'=>'DISPLAY & GAMING: Breathtaking screen refresh rate, adaptive Dynamic AMOLED 2X display, Galaxy 5G support & advanced processor, allow for a smooth gaming experience.', 'product_id'=>1 ],
            [ 'text'=>'INTELLIGENT BATTERY & SUPER FAST CHARGE: All-day intelligent battery learns how to optimize battery life, while super fast charging boosts your battery in minutes.', 'product_id'=>1 ],
            [ 'text'=>'This phone is unlocked and compatible with any carrier of choice on GSM and CDMA networks (e.g. AT&T, T-Mobile, Sprint, Verizon, US Cellular, Cricket, Metro, Tracfone, Mint Mobile, etc.).', 'product_id'=>2 ],
            [ 'text'=>'Backed by a one-year satisfaction guarantee, with free access to Amazon’s Technical Support team throughout the full year and ability to replace or return the product if it does not work as expected.', 'product_id'=>2 ],
            [ 'text'=>'Tested for battery health and guaranteed to come with a battery that exceeds 90% of original capacity.', 'product_id'=>2 ],
            [ 'text'=>'Unlocked and compatible with any carrier of choice on GSM and CDMA networks (e.g. AT&T, T-Mobile, Sprint, Verizon, US Cellular, Cricket, Metro, Tracfone, Mint Mobile, etc.).', 'product_id'=>3 ],
            [ 'text'=>'Tested for battery health and guaranteed to come with a battery that exceeds 90% of original capacity.', 'product_id'=>3 ],
            [ 'text'=>'This device is locked to AT&T only and not compatible with any other carrier.', 'product_id'=>4 ],
            [ 'text'=>'Successfully passed a full diagnostic test which ensures like-new functionality and removal of any prior-user personal information.', 'product_id'=>4 ],
            [ 'text'=>'Tested for battery health and guaranteed to have a minimum battery capacity of 80%.', 'product_id'=>4 ],
            [ 'text'=>'PRO-GRADE CAMERA: Features high-powered, pro lenses for beautiful photographs in any light with 3X optical zoom', 'product_id'=>5 ],
            [ 'text'=>'30X SPACE ZOOM: Zoom in close from afar or magnify details of something nearby with the power of 30X Space Zoom', 'product_id'=>5 ],
            [ 'text'=>'Expansive Screen: See more and do more with the ultimate folding mobile phone screen that puts a super slim tablet right in your pocket', 'product_id'=>6 ],
            [ 'text'=>'Nearly Invisible Camera: Take in an incredible uninterrupted view with a true edge-to-edge viewing experience thanks to our first-ever Under Display Camera', 'product_id'=>6 ],
            [ 'text'=>'120Hz AMOLED 2X Screen: Everything looks brilliant on this big, beautiful, clear display, offering a mesmerizing and dynamic viewing experience', 'product_id'=>6 ],
            [ 'text'=>'Flex Your Best Angle: With Flex Mode, Just Unfold Your Mobile Phone’S Screen To Your Best Angle For Hands-Free Pics And Video Calls; Choose What You Want To Capture, Set It Down, Stand Back And Shoot Your Best Shot', 'product_id'=>7 ],
            [ 'text'=>'NOTE: No Warranty. This device will work with GSM service providers like AT&T, T-Mobile, MetroPCS, and most other GSM service providers. It will not work with CDMA service providers like Verizon, US Cellular, Sprint, or any other CDMA service providers. Please check device compatibility with your cell phone provider before you place your order.', 'product_id'=>8 ],
            [ 'text'=>'Storage: 256GB 8GB RAM', 'product_id'=>8 ],
            [ 'text'=>'Display: 6.6 inches, 105.4 cm2 (~91.2% screen-to-body ratio) OLED, 1B colors, 120Hz', 'product_id'=>8 ],
            [ 'text'=>'Efficient Intel Celeron N4020 Processor (4M Cache, up to 2.8 GHz)', 'product_id'=>9 ],
            [ 'text'=>'NVIDIA GeForce RTX 3050 Ti 4GB GDDR6 up to 1585MHz at 60W (75W with Dynamic Boost 2.0)', 'product_id'=>10 ],
            [ 'text'=>'15.6 inch Full HD OLED NanoEdge bezel display with stunning 85% screen-to-body ratio', 'product_id'=>11 ],
            [ 'text'=>'14 inch 400nits Full HD (1920x1080), Anti-Glare IPS level NanoEdge bezel display', 'product_id'=>12 ],
            [ 'text'=>'Latest 11th generation Intel Core i7-1165G7 Processor (12M Cache, up to 4.7 GHz, with IPU)', 'product_id'=>12 ],
            [ 'text'=>'13.3 inch OLED 400nits Full HD (1920 x 1080) Wide View 4-way NanoEdge bezel display', 'product_id'=>13 ],
            [ 'text'=>'Intel Core i7-1165G7 Processor 2.8 GHz (12M Cache, up to 4.7 GHz, 4 cores)', 'product_id'=>13 ],
            [ 'text'=>'Renewed products look and work like new. These pre-owned products have been inspected and tested by Amazon-qualified suppliers, which typically perform a full diagnostic test, replacement of any defective parts, and a thorough cleaning process. Packaging and accessories may be generic. All products on Amazon Renewed come with a minimum 90-day supplier-backed warranty.', 'product_id'=>14 ],
            [ 'text'=>'ScreenPad Plus: 12.6 inch matte touchscreen, giving your endless way to optimize your multitasking experience by extending the screen or split windows and apps on both displays', 'product_id'=>15 ],
            [ 'text'=>'【Upgraded】RAM is upgraded to 20 GB high-bandwidth RAM to smoothly run multiple applications and browser tabs all at once; Hard Drive is upgraded to 512 GB PCIe NVMe M.2 Solid State Drive to allow faster bootup and data transfer. Original Seal is opened for upgrade ONLY. If the computer has modifications (listed above), then the manufacturer box is opened for it to be tested and inspected and to install the upgrades to achieve the specifications as advertised.', 'product_id'=>16 ],
            [ 'text'=>'【Processor】11th Gen Intel Core i5-1135G7 2.40GHz Quad-Core Processor (8MB Intel Smart Cache, up to 4.20GHz)', 'product_id'=>16 ],
            [ 'text'=>'The IdeaPad 3 15-inch laptop delivers performance with a purpose, driven by the AMD Ryzen 5 5500U mobile processor, 8GB DDR4 memory, and 512GB SSD storage', 'product_id'=>17 ],
            [ 'text'=>'Dolby Audio delivers crystal-clear sound through 2 x 1.5W speakers. Whether you\'re watching a video, streaming music, or video-chatting, you’re sure to love what you hear', 'product_id'=>17 ],
            [ 'text'=>'AMD Ryzen 5 5500U (6-Core) Processor', 'product_id'=>18 ],
            [ 'text'=>'27-inch desktop business monitor with 1800R ultra-curved screen; provides an immersive, natural viewing experience for enhanced productivity and reduced eye fatigue', 'product_id'=>19 ],
            [ 'text'=>'Full HD 1920 x 1080 resolution with a 16:9 aspect ratio. Samsung VA panel delivers deep blacks, vivid colors, and a wide viewing angle, while Eye Saver Mode and Flicker-Free technology help minimize eye strain during long working hours', 'product_id'=>19 ],
            [ 'text'=>'27 inch WQHD (2560x1440) IPS gaming monitor with 1ms (MPRT) response time 165Hz refresh rate (supports 144Hz) and G-SYNC compatibility for a tear-free experience', 'product_id'=>20 ],
            [ 'text'=>'27-inch WQHD (2560 x 1440) LED backlight display with IPS 178° wide viewing angle panel International color standard 100% sRGB and 100% Rec. 709 wide color gamut', 'product_id'=>21 ],
            [ 'text'=>'23.8-inch Full HD (1920x1080) LED backlight display with IPS 178° wide viewing angle panel', 'product_id'=>22 ],
            [ 'text'=>'Up to 75Hz refresh rate with Adaptive-Sync/FreeSync technology to eliminate tracing and ensure crisp and clear video playback', 'product_id'=>22 ],
            [ 'text'=>'Feel the power of extra bass', 'product_id'=>23 ],
            [ 'text'=>'Wireless Audio with Bluetooth technology', 'product_id'=>23 ],
            [ 'text'=>'EASY WIRELESS CONNECTIVITY - Radio Frequency Headphones Let You Move Freely Up to 150 SENSATIONAL HD PERFORMANCE - Sony Technology Produces High Fidelity Sound & Booming Bass w/ Noise Reduction, Voice Mode, Volume Control & Auto TuneFt Through Walls & Ceiling; Battery Life Up to 20 Hours Per Charge', 'product_id'=>24 ],
            [ 'text'=>'TRULY WIRELESS: Compatible with Apple or Android cell phones, sync using Bluetooth connection & NFC', 'product_id'=>25 ],
            [ 'text'=>'DIGITAL NOISE CANCELING: WF-SP700N headphone set minimizes distractions & noises for crisp listening', 'product_id'=>25 ],
            [ 'text'=>'Lightweight 1.38 in neodymium dynamic drivers deliver a punchy, rhythmic response to even the most demanding tracks. Driver Unit: Dome type', 'product_id'=>26 ],
            [ 'text'=>'The swiveling earcup design allows easy storage when you’re not using them, and enhances portability when you’re traveling', 'product_id'=>26 ],
        ]);

        DB::table('users')->insert([
            'name' => 'Erfan',
            'email' => 'landa.cloner1379@gmail.com',
            'phone' => '09036583793' ,
            'password' => '$2y$10$6c7oV9VWohgVBJ2z2Xe8z.EnSLOn8new/wm5ZmnpHRpgUsb8bsXJG'
        ]);

        DB::table('addresses')->insert([
            [ 'address'=>'Khazaneh Bokharaei P30 V8', 'zipcode'=>1111111112, 'user_id'=>1, 'country'=>'Iran', 'city'=>'tehran', 'receiver_name'=>'Erfan Rasooli', 'receiver_phone'=>'09036583793', ],
            [ 'address'=>'Hasan Abad YazdChi SheShgelani P42 V4', 'zipcode'=>1876543211, 'user_id'=>1, 'country'=>'Iran', 'city'=>'Tehran', 'receiver_name'=>'Mahdi Lapechi', 'receiver_phone'=>'09211223430', ],
            [ 'address'=>'Vahdat Eslami Payeein Tar az Charsou PirBaba', 'zipcode'=>1234567891, 'user_id'=>1, 'country'=>'Iran', 'city'=>'Tehran', 'receiver_name'=>'Hamid Rahimi', 'receiver_phone'=>'09191387654', ],
            [ 'address'=>'Yazdchi nineclani P43 A1', 'zipcode'=>1324562754, 'user_id'=>1, 'country'=>'Amrica', 'city'=>'NewYork', 'receiver_name'=>'Black Michel', 'receiver_phone'=>'09128756432', ],
        ]);

        DB::table('admins')->insert([
            'name' => 'Erfan',
            'email' => 'landa.cloner1379@gmail.com',
            'phone' => null ,
            'password' => '$2y$10$6c7oV9VWohgVBJ2z2Xe8z.EnSLOn8new/wm5ZmnpHRpgUsb8bsXJG'
        ]);

        DB::table('details')->insert([
            [ 'key'=>'Model Name', 'subcategory_id'=>1 ],
            [ 'key'=>'Wireless Carrier', 'subcategory_id'=>1 ],
            [ 'key'=>'Brand', 'subcategory_id'=>1 ],
            [ 'key'=>'Form Factor', 'subcategory_id'=>1 ],
            [ 'key'=>'Memory Storage Capacity', 'subcategory_id'=>1 ],
            [ 'key'=>'Operating System', 'subcategory_id'=>1 ],
            [ 'key'=>'Color', 'subcategory_id'=>1 ],
            [ 'key'=>'Cellular Technology', 'subcategory_id'=>1 ],
            [ 'key'=>'Screen Size', 'subcategory_id'=>1 ],
            [ 'key'=>'Included Components', 'subcategory_id'=>1 ],
            [ 'key'=>'Display Type', 'subcategory_id'=>1 ],
            [ 'key'=>'Series', 'subcategory_id'=>2 ],
            [ 'key'=>'Brand', 'subcategory_id'=>2 ],
            [ 'key'=>'Specific Uses For Product', 'subcategory_id'=>2 ],
            [ 'key'=>'Screen Size', 'subcategory_id'=>2 ],
            [ 'key'=>'Operating System', 'subcategory_id'=>2 ],
            [ 'key'=>'CPU Manufacturer', 'subcategory_id'=>2 ],
            [ 'key'=>'Card Description', 'subcategory_id'=>2 ],
            [ 'key'=>'Color', 'subcategory_id'=>2 ],
            [ 'key'=>'Hard Disk Size', 'subcategory_id'=>2 ],
            [ 'key'=>'Processor Count', 'subcategory_id'=>2 ],
            [ 'key'=>'Connectivity Technology', 'subcategory_id'=>2 ],
            [ 'key'=>'Specific Uses For Product', 'subcategory_id'=>3 ],
            [ 'key'=>'Refresh Rate', 'subcategory_id'=>3 ],
            [ 'key'=>'Brand', 'subcategory_id'=>3 ],
            [ 'key'=>'Screen Size', 'subcategory_id'=>3 ],
            [ 'key'=>'Screen Surface Description', 'subcategory_id'=>3 ],
            [ 'key'=>'Brand', 'subcategory_id'=>4 ],
            [ 'key'=>'Color', 'subcategory_id'=>4 ],
            [ 'key'=>'Connectivity Technology', 'subcategory_id'=>4 ],
            [ 'key'=>'new', 'subcategory_id'=>1 ],

        ]);

        DB::table('detail_product')->insert([
            [ 'value'=>'Note 20 Ultra 5G', 'detail_id'=>1, 'product_id'=>1 ],
            [ 'value'=>'Unlocked', 'detail_id'=>2, 'product_id'=>1 ],
            [ 'value'=>'Samsung Electronics', 'detail_id'=>3, 'product_id'=>1 ],
            [ 'value'=>'Smartphone', 'detail_id'=>4, 'product_id'=>1 ],
            [ 'value'=>'128 GB', 'detail_id'=>5, 'product_id'=>1 ],
            [ 'value'=>'Android', 'detail_id'=>6, 'product_id'=>1 ],
            [ 'value'=>'Mystic White', 'detail_id'=>7, 'product_id'=>1 ],
            [ 'value'=>'5G', 'detail_id'=>8, 'product_id'=>1 ],
            [ 'value'=>'6.9 Inches', 'detail_id'=>9, 'product_id'=>1 ],
            [ 'value'=>'IPhone 11 Pro', 'detail_id'=>1, 'product_id'=>2 ],
            [ 'value'=>'Unlocked for All Carriers', 'detail_id'=>2, 'product_id'=>2 ],
            [ 'value'=>'Apple', 'detail_id'=>3, 'product_id'=>2 ],
            [ 'value'=>'Smart Phone', 'detail_id'=>4, 'product_id'=>2 ],
            [ 'value'=>'64 GB', 'detail_id'=>5, 'product_id'=>2 ],
            [ 'value'=>'IOS 12', 'detail_id'=>6, 'product_id'=>2 ],
            [ 'value'=>'Space Gray', 'detail_id'=>7, 'product_id'=>2 ],
            [ 'value'=>'4G', 'detail_id'=>8, 'product_id'=>2 ],
            [ 'value'=>'Charging cable and block', 'detail_id'=>10, 'product_id'=>2 ],
            [ 'value'=>'LED', 'detail_id'=>11, 'product_id'=>2 ],
            [ 'value'=>'IPhone 12 Pro', 'detail_id'=>1, 'product_id'=>3 ],
            [ 'value'=>'Unlocked', 'detail_id'=>2, 'product_id'=>3 ],
            [ 'value'=>'Apple', 'detail_id'=>3, 'product_id'=>3 ],
            [ 'value'=>'Smartphone', 'detail_id'=>4, 'product_id'=>3 ],
            [ 'value'=>'128 GB', 'detail_id'=>5, 'product_id'=>3 ],
            [ 'value'=>'IOS 12', 'detail_id'=>6, 'product_id'=>3 ],
            [ 'value'=>'Pacific Blue', 'detail_id'=>7, 'product_id'=>3 ],
            [ 'value'=>'LTE', 'detail_id'=>8, 'product_id'=>3 ],
            [ 'value'=>'IPhone 8 Plus', 'detail_id'=>1, 'product_id'=>4 ],
            [ 'value'=>'AT&T', 'detail_id'=>2, 'product_id'=>4 ],
            [ 'value'=>'Apple', 'detail_id'=>3, 'product_id'=>4 ],
            [ 'value'=>'Smartphone', 'detail_id'=>4, 'product_id'=>4 ],
            [ 'value'=>'64 GB', 'detail_id'=>5, 'product_id'=>4 ],
            [ 'value'=>'IOS', 'detail_id'=>6, 'product_id'=>4 ],
            [ 'value'=>'Gold', 'detail_id'=>7, 'product_id'=>4 ],
            [ 'value'=>'4G', 'detail_id'=>8, 'product_id'=>4 ],
            [ 'value'=>'S20FE', 'detail_id'=>1, 'product_id'=>5 ],
            [ 'value'=>'Unlocked', 'detail_id'=>2, 'product_id'=>5 ],
            [ 'value'=>'Samsung Electronics', 'detail_id'=>3, 'product_id'=>5 ],
            [ 'value'=>'Smartphone', 'detail_id'=>4, 'product_id'=>5 ],
            [ 'value'=>'128 GB', 'detail_id'=>5, 'product_id'=>5 ],
            [ 'value'=>'Android', 'detail_id'=>6, 'product_id'=>5 ],
            [ 'value'=>'Cloud Navy', 'detail_id'=>7, 'product_id'=>5 ],
            [ 'value'=>'5G', 'detail_id'=>8, 'product_id'=>5 ],
            [ 'value'=>'Z Fold 3 5G', 'detail_id'=>1, 'product_id'=>6 ],
            [ 'value'=>'Unlocked', 'detail_id'=>2, 'product_id'=>6 ],
            [ 'value'=>'Samsung Electronics', 'detail_id'=>3, 'product_id'=>6 ],
            [ 'value'=>'Foldable Screen', 'detail_id'=>4, 'product_id'=>6 ],
            [ 'value'=>'12 GB', 'detail_id'=>5, 'product_id'=>6 ],
            [ 'value'=>'Android', 'detail_id'=>6, 'product_id'=>6 ],
            [ 'value'=>'Phantom Black', 'detail_id'=>7, 'product_id'=>6 ],
            [ 'value'=>'5G', 'detail_id'=>8, 'product_id'=>6 ],
            [ 'value'=>'Z Flip 3 5G', 'detail_id'=>1, 'product_id'=>7 ],
            [ 'value'=>'Unlocked', 'detail_id'=>2, 'product_id'=>7 ],
            [ 'value'=>'Samsung Electronics', 'detail_id'=>3, 'product_id'=>7 ],
            [ 'value'=>'Flip', 'detail_id'=>4, 'product_id'=>7 ],
            [ 'value'=>'8 GB', 'detail_id'=>5, 'product_id'=>7 ],
            [ 'value'=>'Android', 'detail_id'=>6, 'product_id'=>7 ],
            [ 'value'=>'Green', 'detail_id'=>7, 'product_id'=>7 ],
            [ 'value'=>'P50 Pro', 'detail_id'=>1, 'product_id'=>8 ],
            [ 'value'=>'T-Mobile', 'detail_id'=>2, 'product_id'=>8 ],
            [ 'value'=>'HUAWEI', 'detail_id'=>3, 'product_id'=>8 ],
            [ 'value'=>'Gold', 'detail_id'=>7, 'product_id'=>8 ],
            [ 'value'=>'256 GB', 'detail_id'=>5, 'product_id'=>8 ],
            [ 'value'=>'Android', 'detail_id'=>6, 'product_id'=>8 ],
            [ 'value'=>'L510MA-DS04', 'detail_id'=>12, 'product_id'=>9 ],
            [ 'value'=>'ASUS', 'detail_id'=>13, 'product_id'=>9 ],
            [ 'value'=>'Personal, Gaming, Business', 'detail_id'=>14, 'product_id'=>9 ],
            [ 'value'=>'15.6', 'detail_id'=>15, 'product_id'=>9 ],
            [ 'value'=>'Windows 10 Home', 'detail_id'=>16, 'product_id'=>9 ],
            [ 'value'=>'Intel', 'detail_id'=>17, 'product_id'=>9 ],
            [ 'value'=>'Integrated', 'detail_id'=>18, 'product_id'=>9 ],
            [ 'value'=>'Black', 'detail_id'=>19, 'product_id'=>9 ],
            [ 'value'=>'128 GB', 'detail_id'=>20, 'product_id'=>9 ],
            [ 'value'=>'ASUS TUF Dash', 'detail_id'=>12, 'product_id'=>10 ],
            [ 'value'=>'ASUS', 'detail_id'=>13, 'product_id'=>10 ],
            [ 'value'=>'Personal, Gaming, Business', 'detail_id'=>14, 'product_id'=>10 ],
            [ 'value'=>'15.6 Inches', 'detail_id'=>15, 'product_id'=>10 ],
            [ 'value'=>'Windows 10 Home', 'detail_id'=>16, 'product_id'=>10 ],
            [ 'value'=>'Intel', 'detail_id'=>17, 'product_id'=>10 ],
            [ 'value'=>'GeForce RTX 3050 Ti', 'detail_id'=>18, 'product_id'=>10 ],
            [ 'value'=>'Eclipse Grey', 'detail_id'=>19, 'product_id'=>10 ],
            [ 'value'=>'1 TB', 'detail_id'=>20, 'product_id'=>10 ],
            [ 'value'=>'ASUS VivoBook 15', 'detail_id'=>12, 'product_id'=>11 ],
            [ 'value'=>'ASUS', 'detail_id'=>13, 'product_id'=>11 ],
            [ 'value'=>'Personal, Student, Business', 'detail_id'=>14, 'product_id'=>11 ],
            [ 'value'=>'Windows 10 Home', 'detail_id'=>16, 'product_id'=>11 ],
            [ 'value'=>'Intel', 'detail_id'=>17, 'product_id'=>11 ],
            [ 'value'=>'Intel Iris Xe', 'detail_id'=>18, 'product_id'=>11 ],
            [ 'value'=>'UX425EA-EH71', 'detail_id'=>12, 'product_id'=>12 ],
            [ 'value'=>'ASUS', 'detail_id'=>13, 'product_id'=>12 ],
            [ 'value'=>'Multimedia, Personal, Business', 'detail_id'=>14, 'product_id'=>12 ],
            [ 'value'=>'14', 'detail_id'=>15, 'product_id'=>12 ],
            [ 'value'=>'Windows 10 Home', 'detail_id'=>16, 'product_id'=>12 ],
            [ 'value'=>'Iris Xe Graphic', 'detail_id'=>18, 'product_id'=>12 ],
            [ 'value'=>'Pine Grey', 'detail_id'=>19, 'product_id'=>12 ],
            [ 'value'=>'ZenBook 13', 'detail_id'=>12, 'product_id'=>13 ],
            [ 'value'=>'ASUS', 'detail_id'=>13, 'product_id'=>13 ],
            [ 'value'=>'Personal, Gaming, Business', 'detail_id'=>14, 'product_id'=>13 ],
            [ 'value'=>'13.3 Inches', 'detail_id'=>15, 'product_id'=>13 ],
            [ 'value'=>'512 GB', 'detail_id'=>20, 'product_id'=>13 ],
            [ 'value'=>'4', 'detail_id'=>21, 'product_id'=>13 ],
            [ 'value'=>'Macbook Air', 'detail_id'=>12, 'product_id'=>14 ],
            [ 'value'=>'Apple', 'detail_id'=>13, 'product_id'=>14 ],
            [ 'value'=>'Business', 'detail_id'=>14, 'product_id'=>14 ],
            [ 'value'=>'13.3 Inches', 'detail_id'=>15, 'product_id'=>14 ],
            [ 'value'=>'MAC OS X', 'detail_id'=>16, 'product_id'=>14 ],
            [ 'value'=>'Intel', 'detail_id'=>17, 'product_id'=>14 ],
            [ 'value'=>'Silver', 'detail_id'=>19, 'product_id'=>14 ],
            [ 'value'=>'ASUS ZenBook', 'detail_id'=>12, 'product_id'=>15 ],
            [ 'value'=>'ASUS', 'detail_id'=>13, 'product_id'=>15 ],
            [ 'value'=>'1 TB', 'detail_id'=>20, 'product_id'=>15 ],
            [ 'value'=>'14 Inches', 'detail_id'=>15, 'product_id'=>15 ],
            [ 'value'=>'Windows 10 Pro', 'detail_id'=>16, 'product_id'=>15 ],
            [ 'value'=>'Intel', 'detail_id'=>17, 'product_id'=>15 ],
            [ 'value'=>'GeForce MX450', 'detail_id'=>18, 'product_id'=>15 ],
            [ 'value'=>'IdeaPad', 'detail_id'=>12, 'product_id'=>16 ],
            [ 'value'=>'Lenovo', 'detail_id'=>13, 'product_id'=>16 ],
            [ 'value'=>'4', 'detail_id'=>21, 'product_id'=>16 ],
            [ 'value'=>'15.6 Inches', 'detail_id'=>15, 'product_id'=>16 ],
            [ 'value'=>'Windows 11', 'detail_id'=>16, 'product_id'=>16 ],
            [ 'value'=>'Arctic Grey', 'detail_id'=>19, 'product_id'=>16 ],
            [ 'value'=>'Intel', 'detail_id'=>17, 'product_id'=>16 ],
            [ 'value'=>'Ideapad 3 15 Laptop', 'detail_id'=>12, 'product_id'=>17 ],
            [ 'value'=>'Lenovo', 'detail_id'=>13, 'product_id'=>17 ],
            [ 'value'=>'Personal', 'detail_id'=>14, 'product_id'=>17 ],
            [ 'value'=>'15.6 Inches', 'detail_id'=>15, 'product_id'=>17 ],
            [ 'value'=>'AMD', 'detail_id'=>17, 'product_id'=>17 ],
            [ 'value'=>'Abyss Blue', 'detail_id'=>19, 'product_id'=>17 ],
            [ 'value'=>'Windows 11', 'detail_id'=>16, 'product_id'=>17 ],
            [ 'value'=>'1', 'detail_id'=>21, 'product_id'=>17 ],
            [ 'value'=>'Lenovo Ideapad', 'detail_id'=>12, 'product_id'=>18 ],
            [ 'value'=>'Lenovo', 'detail_id'=>13, 'product_id'=>18 ],
            [ 'value'=>'15.6 Inches', 'detail_id'=>15, 'product_id'=>18 ],
            [ 'value'=>'Windows', 'detail_id'=>16, 'product_id'=>18 ],
            [ 'value'=>'AMD', 'detail_id'=>17, 'product_id'=>18 ],
            [ 'value'=>'512 GB', 'detail_id'=>20, 'product_id'=>18 ],
            [ 'value'=>'Multimedia, Personal, Business', 'detail_id'=>23, 'product_id'=>19 ],
            [ 'value'=>'60 Hz', 'detail_id'=>24, 'product_id'=>19 ],
            [ 'value'=>'Samsung Business', 'detail_id'=>25, 'product_id'=>19 ],
            [ 'value'=>'27 Inches', 'detail_id'=>26, 'product_id'=>19 ],
            [ 'value'=>'Curved', 'detail_id'=>27, 'product_id'=>19 ],
            [ 'value'=>'Personal, Gaming, Business', 'detail_id'=>23, 'product_id'=>20 ],
            [ 'value'=>'165 Hz', 'detail_id'=>24, 'product_id'=>20 ],
            [ 'value'=>'ASUS', 'detail_id'=>25, 'product_id'=>20 ],
            [ 'value'=>'27 Inches', 'detail_id'=>26, 'product_id'=>20 ],
            [ 'value'=>'Matte', 'detail_id'=>27, 'product_id'=>20 ],
            [ 'value'=>'Personal, Gaming, Business', 'detail_id'=>23, 'product_id'=>21 ],
            [ 'value'=>'75 Hz', 'detail_id'=>24, 'product_id'=>21 ],
            [ 'value'=>'ASUS', 'detail_id'=>25, 'product_id'=>21 ],
            [ 'value'=>'27 Inches', 'detail_id'=>26, 'product_id'=>21 ],
            [ 'value'=>'Flat', 'detail_id'=>27, 'product_id'=>21 ],
            [ 'value'=>'Personal, Gaming, Business', 'detail_id'=>23, 'product_id'=>22 ],
            [ 'value'=>'75 Hz', 'detail_id'=>24, 'product_id'=>22 ],
            [ 'value'=>'ASUS', 'detail_id'=>25, 'product_id'=>22 ],
            [ 'value'=>'24 Inches', 'detail_id'=>26, 'product_id'=>22 ],
            [ 'value'=>'Flat', 'detail_id'=>27, 'product_id'=>22 ],
            [ 'value'=>'Sony', 'detail_id'=>28, 'product_id'=>23 ],
            [ 'value'=>'Blue', 'detail_id'=>29, 'product_id'=>23 ],
            [ 'value'=>'Wireless', 'detail_id'=>30, 'product_id'=>23 ],
            [ 'value'=>'Sony', 'detail_id'=>28, 'product_id'=>24 ],
            [ 'value'=>'Gray', 'detail_id'=>29, 'product_id'=>24 ],
            [ 'value'=>'Wireless', 'detail_id'=>30, 'product_id'=>24 ],
            [ 'value'=>'Sony', 'detail_id'=>28, 'product_id'=>25 ],
            [ 'value'=>'Black', 'detail_id'=>29, 'product_id'=>25 ],
            [ 'value'=>'Wireless', 'detail_id'=>30, 'product_id'=>25 ],
            [ 'value'=>'Sony', 'detail_id'=>28, 'product_id'=>26 ],
            [ 'value'=>'Black', 'detail_id'=>29, 'product_id'=>26 ],
            [ 'value'=>'Wired', 'detail_id'=>30, 'product_id'=>26 ],
        ]);

        DB::table('images')->insert([
            [ 'file'=>'public/images/8KnPP3IoqrMoCekwDY03w8DfM2SwOPFmZ9bY9rRS.jpg', 'order'=>1, 'product_id'=>1 ],
            [ 'file'=>'public/images/ZrjbJPpQXTxwoXPCTHfvTFPSlwlWNSgbp2qA5i9E.jpg', 'order'=>2, 'product_id'=>1 ],
            [ 'file'=>'public/images/KYwf7dk6QIYosChGV7CTDWurwD5pyyp6AprHWzit.jpg', 'order'=>3, 'product_id'=>1 ],
            [ 'file'=>'public/images/eXMcULPCMsJjrT4laEUrbA0xV8aqUXRRCZeF2it9.jpg', 'order'=>4, 'product_id'=>1 ],
            [ 'file'=>'public/images/fuWIJMNCLSTEs3ftsBCEtucZR24uKJSjQhdIxytH.jpg', 'order'=>1, 'product_id'=>2 ],
            [ 'file'=>'public/images/vkriitw5kgoXKZvlyekJ9QnINcT2loTMyzv6j4Lh.jpg', 'order'=>2, 'product_id'=>2 ],
            [ 'file'=>'public/images/Q53KqlLCh3nROhVAnKvFddZuzLQfoajqaHyVsmJY.jpg', 'order'=>3, 'product_id'=>2 ],
            [ 'file'=>'public/images/0Is5tTuQP165jZB195WFu0xKIxWnzwAQhLroCBnq.jpg', 'order'=>4, 'product_id'=>2 ],
            [ 'file'=>'public/images/zZNhorkhg5sgjqZefjxOLou0IfrWebCDZj2Q5BJ5.jpg', 'order'=>5, 'product_id'=>2 ],
            [ 'file'=>'public/images/HaLoisyfJs7YSj0705MGVHYrgb6X7NrUhPokxYfz.jpg', 'order'=>6, 'product_id'=>2 ],
            [ 'file'=>'public/images/FPWlLIcIsJfLEwe8rEfliThiYdDce57GcVpOTWDN.jpg', 'order'=>1, 'product_id'=>3 ],
            [ 'file'=>'public/images/BP3E7KVoZZuIPubrYzgYeLa5ZxfUjj1pkfcjhHib.jpg', 'order'=>1, 'product_id'=>4 ],
            [ 'file'=>'public/images/nD3W0DeH2X766Y74OyAnBJwfZpRyPO9DBrPYW4wv.jpg', 'order'=>1, 'product_id'=>5 ],
            [ 'file'=>'public/images/tkMoBpIIWZjOriGMefxA37iwJ2smPVVRHcILBshq.jpg', 'order'=>2, 'product_id'=>5 ],
            [ 'file'=>'public/images/3AYyjIFE2vfWatiKNCuM2ywP1jYQeeNnzoIpGafE.jpg', 'order'=>3, 'product_id'=>5 ],
            [ 'file'=>'public/images/h78D2hckyUVRekw1PxPM8BuNCevvgsVkImAgdVpT.jpg', 'order'=>1, 'product_id'=>6 ],
            [ 'file'=>'public/images/THpmydmrviR33sDdtZvu7NvgOEDObhCeo4ES5lsm.jpg', 'order'=>2, 'product_id'=>6 ],
            [ 'file'=>'public/images/zXBCPXPBoTvAZyQjJ5xOZdIwiZXWqPlHNmwFaZ6a.jpg', 'order'=>3, 'product_id'=>6 ],
            [ 'file'=>'public/images/x0ueb9UCzwjRDjZ4XB4ruSnleefU54emTNp7qkP6.jpg', 'order'=>1, 'product_id'=>7 ],
            [ 'file'=>'public/images/Nmu7ZDhHlD6CicaQqLElVD15pkCw2HWHMv44TfjT.jpg', 'order'=>2, 'product_id'=>7 ],
            [ 'file'=>'public/images/IzBmW0smKECtO4UUDglTLd7kHjI8UGAHFvftp2ry.jpg', 'order'=>3, 'product_id'=>7 ],
            [ 'file'=>'public/images/gvB3HEzqY66U9FSKXC2EyUxbxCI6H2Ny2nmj7GT0.jpg', 'order'=>4, 'product_id'=>7 ],
            [ 'file'=>'public/images/JDzAvKniylaLGInGh9yh4OmOLuyXEI8jLSlb5zav.jpg', 'order'=>5, 'product_id'=>7 ],
            [ 'file'=>'public/images/Bc8RtDaeIBMeuXA0pOiy0xNiYMA0KsSamkXX9Idl.jpg', 'order'=>1, 'product_id'=>8 ],
            [ 'file'=>'public/images/jkXp6BU8jAZqbkvPtejGeag3w9bPFJuUs8a3tk2I.jpg', 'order'=>1, 'product_id'=>9 ],
            [ 'file'=>'public/images/LWdxy5ncSWkzuu2Q8BE0OY4IjX1j7PX3b05Qfdgt.jpg', 'order'=>2, 'product_id'=>9 ],
            [ 'file'=>'public/images/4bUH3rd1wGI2eDI6mpTbIwBuu1DFEt5sE0ZyC8iV.jpg', 'order'=>3, 'product_id'=>9 ],
            [ 'file'=>'public/images/el0ytCzq44AiaPl2BGDjrWsDdaA0nwxvM3wmhhJD.jpg', 'order'=>1, 'product_id'=>10 ],
            [ 'file'=>'public/images/71rUSbDfeuzSoyZDVW0fvBWzq0ElXi9KCoJe5RsR.jpg', 'order'=>2, 'product_id'=>10 ],
            [ 'file'=>'public/images/t2UoYHJJfOo4xJY5UVDFktXMwh2ANdLaek4tT94K.jpg', 'order'=>3, 'product_id'=>10 ],
            [ 'file'=>'public/images/4ksjX8gLW0QmLmAfYaHxAEd3RIte0LDlkKGeOfJW.jpg', 'order'=>4, 'product_id'=>10 ],
            [ 'file'=>'public/images/37vt6AHCd08KwWq4Hdu55EKAS2sgqxNi8tiZDEDD.jpg', 'order'=>1, 'product_id'=>11 ],
            [ 'file'=>'public/images/jKpitwOs8AtaWefUmu3iHlSGIS4F5C7aW3vN7hLe.jpg', 'order'=>2, 'product_id'=>11 ],
            [ 'file'=>'public/images/wV2yXbf2vXqPSvmNqgOBMzbJC8XxzaPJHqE32Se4.jpg', 'order'=>3, 'product_id'=>11 ],
            [ 'file'=>'public/images/EE8DPm90FlI3E4YVWGrMv1a7rZOZm2rGd0AXEXc2.jpg', 'order'=>1, 'product_id'=>12 ],
            [ 'file'=>'public/images/seGtp07LUd82u43pDiCC9l1C6dSeZcPkaFqUn6VD.jpg', 'order'=>2, 'product_id'=>12 ],
            [ 'file'=>'public/images/Iw9HAkPAy2AIe0rY63EUwfARfiLpseSGyMeCilzJ.jpg', 'order'=>3, 'product_id'=>12 ],
            [ 'file'=>'public/images/GgoXmdZirIU30yG5yr984TtEdRR6xwGWQyhxuCxw.jpg', 'order'=>4, 'product_id'=>12 ],
            [ 'file'=>'public/images/xpSqK6ut8uAOODE3bdQ8Q2t7o8JTOHKsqRWrnacf.jpg', 'order'=>1, 'product_id'=>13 ],
            [ 'file'=>'public/images/eVAl8oJHSJxIrLobM4MQzGjv9gSEqZbeZykDf0NA.jpg', 'order'=>2, 'product_id'=>13 ],
            [ 'file'=>'public/images/P1yKA6DhIG0G3ZJYfummxiFac21DG7H4J8k3XlSf.jpg', 'order'=>3, 'product_id'=>13 ],
            [ 'file'=>'public/images/Tilm1CDTtTYl65OxOXgs5OiZspLbLiht14ZoBq8Z.jpg', 'order'=>1, 'product_id'=>14 ],
            [ 'file'=>'public/images/Fm5wspD8TUGrVe9SieEmn3vXriRwS1ywMVbiGL2c.jpg', 'order'=>2, 'product_id'=>14 ],
            [ 'file'=>'public/images/Jm74FkdE0PJNonV0YNK7JQ6Z1GIDIGe46zma1wh8.jpg', 'order'=>3, 'product_id'=>14 ],
            [ 'file'=>'public/images/detn07XHKZJGVXfAoKraPRXyVjVkm64PlRiFcqmy.jpg', 'order'=>4, 'product_id'=>14 ],
            [ 'file'=>'public/images/yTlCePyysjGSpwwANgCTCaYHyhJhWSWJgjRvu8Ds.jpg', 'order'=>1, 'product_id'=>15 ],
            [ 'file'=>'public/images/xMQVjWtxGNeiCp4g5VAfKioOBi1RZbYLzBKOWY1O.jpg', 'order'=>2, 'product_id'=>15 ],
            [ 'file'=>'public/images/Cg8UGwocItpjrJDNbdOIIkXlJTjkKuRPtYxla3zT.jpg', 'order'=>3, 'product_id'=>15 ],
            [ 'file'=>'public/images/bMatlloTt6xOV2va1TNYlwi5l5PcluctY5pg8ZOL.jpg', 'order'=>4, 'product_id'=>15 ],
            [ 'file'=>'public/images/fQNZ5dluq3BgGLgS0bzPIh1Wyfs1fxeAnziZeAeQ.jpg', 'order'=>1, 'product_id'=>16 ],
            [ 'file'=>'public/images/DS1HumW7jt3YsK1ibVsEak8bu4OmH6AWfCHQlGRc.jpg', 'order'=>2, 'product_id'=>16 ],
            [ 'file'=>'public/images/BGUgHKL4zaFt4kpxEvB8TdV0dJ3sRGlmWfYCcS1m.jpg', 'order'=>3, 'product_id'=>16 ],
            [ 'file'=>'public/images/dKmVbyIiUL44hT9SJA2teGUX8QpqNyqEy0Tyg90V.jpg', 'order'=>1, 'product_id'=>17 ],
            [ 'file'=>'public/images/bdsUl8OeYtOZYUQiKaS5LkdWXgYTAjIh5oDazBXM.jpg', 'order'=>2, 'product_id'=>17 ],
            [ 'file'=>'public/images/Wbrl96KGsZCqWBaWveDgMrN60jwxTe9JyXaOVbX9.jpg', 'order'=>3, 'product_id'=>17 ],
            [ 'file'=>'public/images/rIrxyFMaAtzDdTTZfuGBvZmVVPjlHY4s8MlVruFd.jpg', 'order'=>1, 'product_id'=>18 ],
            [ 'file'=>'public/images/wiS58KWEjzxGxmykDaMUGWjdoY4by2JPNboVVE6Y.jpg', 'order'=>2, 'product_id'=>18 ],
            [ 'file'=>'public/images/vgYIEY7u9FDXCmVkZryomcWFLTCnBeAKDsYZJVft.jpg', 'order'=>3, 'product_id'=>18 ],
            [ 'file'=>'public/images/xFP1hauXNDU8HVenPGj9LOVNKJWeSFVrVrrMdoe3.jpg', 'order'=>1, 'product_id'=>19 ],
            [ 'file'=>'public/images/GU7EWjVeTiMehXizGJeMVZLsYrztUTi5KwviBZXl.jpg', 'order'=>2, 'product_id'=>19 ],
            [ 'file'=>'public/images/GqRof1oFUN8mNdRbCKw3kZ7sKKgjYk5pHZArJQk1.jpg', 'order'=>3, 'product_id'=>19 ],
            [ 'file'=>'public/images/dmxnKCmFQkZcAKXIhqZmGrFOCM7Nk6pS0Yid89Ar.jpg', 'order'=>1, 'product_id'=>20 ],
            [ 'file'=>'public/images/nrzuWRGLNXOvWK2CcMzyAIqr8vjurMpvp9ZxLCAm.jpg', 'order'=>2, 'product_id'=>20 ],
            [ 'file'=>'public/images/lEGCp7F23pGecfk8NsKJlT3oBQfZmQK3pNZzW0St.jpg', 'order'=>3, 'product_id'=>20 ],
            [ 'file'=>'public/images/CAubpKRFKSZG6eouHUaCtWW0ccJnNlqHyGp0OluQ.jpg', 'order'=>1, 'product_id'=>21 ],
            [ 'file'=>'public/images/choI1hUUenLcPyavCPhvOK1Jo8gmXkuptOlT6RyR.jpg', 'order'=>2, 'product_id'=>21 ],
            [ 'file'=>'public/images/3FXHYWoL85vuBjUah64M48kjeAuoyC5lfAQeLKPq.jpg', 'order'=>3, 'product_id'=>21 ],
            [ 'file'=>'public/images/hAvGPAfyZGBUZOhWrMncsqlWZQ3WsDMzC6g7uLSC.jpg', 'order'=>1, 'product_id'=>22 ],
            [ 'file'=>'public/images/rIbMBJwtxlDfTP68kiX0KoOlT16eO2bp7QbaxfpK.jpg', 'order'=>2, 'product_id'=>22 ],
            [ 'file'=>'public/images/2RDyNggfoTsxVyrrvaxmQIVJ0OBCKDQZuMBG7V4S.jpg', 'order'=>3, 'product_id'=>22 ],
            [ 'file'=>'public/images/wMtpdYKWWegP74D8ivtMnkkck33dbHV3l8sI3sud.jpg', 'order'=>1, 'product_id'=>23 ],
            [ 'file'=>'public/images/AR2DGMQ5IjDNq1CVmj5l36RrMly246GrjkScahMu.jpg', 'order'=>2, 'product_id'=>23 ],
            [ 'file'=>'public/images/qJMHtJu6EgNBJiyuinnJyYQJgWI36g1pGUCdUvsM.jpg', 'order'=>3, 'product_id'=>23 ],
            [ 'file'=>'public/images/LvhSXGPOsjhUXviQzIQv0AD1nG7vcUsNY1DzDxh6.jpg', 'order'=>1, 'product_id'=>24 ],
            [ 'file'=>'public/images/pTfRF0NpdaHSDEcDW3QRsnGlepoxpzXkkMOpPZAI.jpg', 'order'=>2, 'product_id'=>24 ],
            [ 'file'=>'public/images/sgMRcY2FUSA7l8b0t1UWwbBHQX7M7lQZZZ6dKkgM.jpg', 'order'=>3, 'product_id'=>24 ],
            [ 'file'=>'public/images/KhfNS6bEL6i9z7EOeGLlnBA91r4q0THfBxQ2R22z.jpg', 'order'=>4, 'product_id'=>24 ],
            [ 'file'=>'public/images/667ca52tEuMF56KFTFQ4oQzwmBeK3ScJ0CNl9QdG.jpg', 'order'=>1, 'product_id'=>25 ],
            [ 'file'=>'public/images/1HpEs75p9iASeTb1Jp2J645PIWTRWuBTFbP8Pf3w.jpg', 'order'=>2, 'product_id'=>25 ],
            [ 'file'=>'public/images/eZ8HdGWh7JQ7c1xCPTjBGy5ysMJ3Kd5qmWipV8KC.jpg', 'order'=>3, 'product_id'=>25 ],
            [ 'file'=>'public/images/2auZqofeqc13ubtFx606J7pBi20lMy05C4f1ZaVf.jpg', 'order'=>4, 'product_id'=>25 ],
            [ 'file'=>'public/images/Ps11U7u0LQYEeNgvQMysf0BjgPrzmn4FfjxIF0Nq.jpg', 'order'=>1, 'product_id'=>26 ],
            [ 'file'=>'public/images/JBttsL7umKIRG5XzY75R0Skpaugwb49OcVTDWbaG.jpg', 'order'=>2, 'product_id'=>26 ],
            [ 'file'=>'public/images/Ilximu7l6xhpCvdnWgL7uMrhteFRjotTckes0RK9.jpg', 'order'=>3, 'product_id'=>26 ],

        ]);
    }
}
